TASK-2095 - Duplicated libraries at opencga/build/libs
opencb/java-common-libs pull request #80
Opened 2023-09-25 08:16 UTC by juanfeSanahuja

TASK-2095 - Duplicated libraries at opencga/build/libs

2023-09-25 08:16 UTC, juanfeSanahuja commented
Task linked: [TASK-2095 Duplicated libraries at opencga/build/libs](https://app.clickup.com/t/36631768/TASK-2095)

2023-10-13 14:53 UTC, imedina approved these changes

2023-10-13 14:54 UTC, imedina approved these changes

2023-10-15 14:39 UTC, j-coll requested changes

2023-10-15 14:39 UTC, j-coll commented on commons-datastore/commons-datastore-core/pom.xml
> -        <dependency>
This `slf4j-simple` dependency is needed for basic logging during testing (thats why it has the scope). I would not remove it.

2023-10-17 13:07 UTC, imedina approved these changes

2023-10-27 11:11 UTC, j-coll submitted a review, later dismissed

2023-10-27 13:49 UTC, imedina submitted a review, later dismissed

2023-11-13 09:58 UTC, merged